# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
public_folder: "/images/uploads"
collections:
  - name: 'meeting'
    label: 'Buluşmalar'
    folder: '_posts/meetings'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: title}
      - { name: categories, widget: "hidden", default: ["Bulusma"]}
      - { name: layout, widget: "hidden", default: "post"}
      - { name: body, widget: "markdown"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      
  - name: 'materials'
    label: 'Materyaller'
    folder: '_posts/materials'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: title}
      - { name: categories, widget: "hidden", default: ["Materyal"]}
      - { name: layout, widget: "hidden", default: "post"}
      - { name: body, widget: "markdown"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}

  - name: 'announcements'
    label: 'Duyurular'
    folder: '_posts/announcements'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: title}
      - { name: categories, widget: "hidden", default: ["Duyuru"]}
      - { name: layout, widget: "hidden", default: "post"}
      - { name: body, widget: "markdown"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
publish_mode: editorial_workflow
